#pragma once
#ifdef TOOLS_ENABLED
#include "ecs_scene.h"
#include "ecs_ui_editor.h"
#include "scene/gui/box_container.h"
#include "scene/gui/option_button.h"
#include "scene/gui/spin_box.h"
#include "scene/gui/tree.h"
#include "scene/gui/line_edit.h"
#include "scene/gui/label.h"
class SkeletonWorkspaceDocking;
class ECSAnimationTimeline;
class ItemList;
class CheckBox;
class EditorFileDialog;
class ConfirmationDialog;
class ECSAnimationCurve;
class MenuButton;
class ColorPickerButton;
class ECSAnimationEditor : public VBoxContainer {
	GDCLASS(ECSAnimationEditor,VBoxContainer);
	friend class ECSAnimationTimeline;
	friend class ECSAnimationCurve;
	SkeletonWorkspaceDocking *workspace_docking=nullptr;
	String skeleton_ai_directory;
	int64_t skeleton_ai_revision=0;
	void skeleton_ai_start();
	void skeleton_ai_stop();
	void skeleton_ai_poll();
	Dictionary skeleton_ai_request(const Dictionary &p_request);
    ConfirmationDialog *preferences_dialog=nullptr,*asset_export_dialog=nullptr;
    OptionButton *preference_scale=nullptr;
    SpinBox *preference_font=nullptr,*preference_spacing=nullptr,*preference_radius=nullptr,*preference_strength=nullptr;
    CheckBox *preference_grid=nullptr;
    LineEdit *preference_directory=nullptr;
    EditorFileDialog *preference_directory_dialog=nullptr;
    void browse_preference_directory();
    void preference_directory_chosen(const String &path);
    Control *preference_pages[5]={};
    ItemList *preference_categories=nullptr,*export_formats=nullptr;
    LineEdit *export_path=nullptr;
    SpinBox *export_scale=nullptr,*export_quality=nullptr;
    CheckBox *export_crop=nullptr,*export_alpha=nullptr,*export_open=nullptr;
    ColorPickerButton *export_background=nullptr;
    Control *export_image_options=nullptr;
    Label *export_path_label=nullptr,*export_description=nullptr,*export_status=nullptr,*preferences_status=nullptr;
    EditorFileDialog *export_file_dialog=nullptr;
    ConfirmationDialog *export_preview_dialog=nullptr;
    void open_preferences();
    void preferences_category(int p_index);
    void reset_preferences();
    void save_preferences();
    void load_workspace_preferences();
    void apply_timeline_spacing(double p_spacing);
    void open_asset_export();
    void export_format_changed(int p_index);
    void browse_export_file();
    void export_file_chosen(const String &p_path);
    void perform_asset_export();
    void confirm_asset_overwrite();
    ConfirmationDialog *export_overwrite_dialog=nullptr;
    String pending_export_path,confirmed_export_path;
    void preview_asset_export();
    void reset_asset_export();
    Ref<Image> prepare_export_image();
    OptionButton *export_animation=nullptr;
    SpinBox *export_fps=nullptr;
    Control *export_motion_options=nullptr;
    bool motion_exporting=false;
    int motion_index=0,motion_count=0,motion_format=0,motion_owner=0;
    double motion_fps=30,motion_saved_time=0;
    String motion_path,motion_directory,motion_saved_state;
    bool motion_saved_mode=false;
    Vector<String> motion_files;
    Vector2i motion_size;
    void start_motion_export(const String &path,int format);
    void capture_motion_frame();
    void finish_motion_export(const String &error=String());
    void cancel_motion_export();

	EditorFileDialog *project_dialog=nullptr;
	ConfirmationDialog *replace_dialog=nullptr;
	bool independent_project=false;
	int project_operation=0,pending_project_operation=0;
	void project_action(int p_action);
	void confirm_project_action();
	void project_file_selected(const String &p_path);
	void adopt_project(const Ref<ECSScene> &p_scene);
	void project_changed();
	void commit_entities(const Array &p_entities,const String &p_label);
	CheckBox *brush_enabled=nullptr;
	OptionButton *brush_bone=nullptr,*curve_interpolation=nullptr;
	SpinBox *brush_radius=nullptr,*brush_strength=nullptr,*curve_ease=nullptr,*ik_x=nullptr,*ik_y=nullptr,*ik_length=nullptr;
	Control *curve_graph=nullptr;
	void configure_brush();
	ECSAnimationTimeline *timeline=nullptr;
	Tree *hierarchy=nullptr;
	void hierarchy_item_button(Object *p_item,int p_column,int p_id,int p_mouse);
	ItemList *animation_list=nullptr;
	Control *animation_property_panel=nullptr,*setup_property_panel=nullptr;
	void build_canvas_tools();
	VBoxContainer *canvas_tool_host=nullptr,*transform_property_host=nullptr;
	void build_slot_tools(BoxContainer *p_parent);
	void refresh_slot_tools();
	void build_slot_hierarchy(const Array &p_entities, const Vector<TreeItem *> &p_rows);
	void slot_action(int p_action);
	ItemList *skin_layers=nullptr;
	OptionButton *skin_attachment_target=nullptr;
	OptionButton *skin_choice=nullptr,*slot_choice=nullptr,*attachment_choice=nullptr,*slot_blend=nullptr;
	LineEdit *skin_name_edit=nullptr,*slot_name_edit=nullptr,*attachment_name_edit=nullptr;
	SpinBox *slot_order=nullptr;
	ColorPickerButton *slot_tint=nullptr;
	bool refreshing_slots=false;
	Button *compensation_tools[2]={};
	Array compensated_pose(int p_entity,const String &p_field,const Vector3 &p_value);
	static Array compensate_pose(const Array &p_before,int p_entity,const String &p_field,const Vector3 &p_value,bool p_bones,bool p_images,String &r_error);
	bool run_compensation_self_test();
	void canvas_tool_action(int p_tool);
	void create_bone_from_drag(const Vector2 &p_start,const Vector2 &p_end);
	void canvas_value_changed(double p_value,int p_field,int p_axis);
	void refresh_canvas_values();
	void refresh_selection_properties();
	void selection_property_changed();
	LineEdit *selection_name=nullptr;
	SpinBox *selection_length=nullptr;
	Control *bone_properties=nullptr;
	Control *pending_property_reveal=nullptr;
	int property_reveal_frames=0;
	SpinBox *canvas_values[7]={};
	Button *canvas_tools[4]={};
	int active_canvas_tool=1;
	bool refreshing_canvas=false;
	SpinBox *frame=nullptr,*loop_start=nullptr,*loop_end=nullptr;
	Button *auto_key=nullptr,*loop_playback=nullptr;
	Button *transform_tools[3]={};
	int playback_direction=1;
	void transport(int p_action);
	void frame_changed(double p_frame);
	double timeline_fps=30;
	Label *timeline_fps_label=nullptr;
	static double detect_timeline_fps(const Ref<Animation> &p_clip);
	void show_curve_graph();
	void timeline_action(int p_action);
	bool timeline_locked=false;
	int timeline_drag_mode=0;
	Variant copied_key;
	double copied_transition=1;
	LineEdit *hierarchy_search=nullptr;
	MenuButton *hierarchy_filter=nullptr;
	Button *hierarchy_quick[3]={};
	bool hierarchy_types[5]={true,true,true,true,true};
	bool hierarchy_case=false, hierarchy_exact=false;
	Vector<int> selection_history;
	int selection_history_cursor=-1;
	bool navigating_history=false;
	ConfirmationDialog *find_dialog=nullptr;
	LineEdit *find_text=nullptr,*replace_text=nullptr;
	CheckBox *find_case=nullptr,*find_first=nullptr,*find_regex=nullptr;
	ItemList *find_scope=nullptr,*find_types=nullptr;
	Tree *find_results=nullptr;
	Label *find_status=nullptr;
	int64_t find_revision=-1;
	Array find_candidates;
	Label *build_panel_header(BoxContainer *p_parent,const String &p_title,const String &p_icon,bool p_animation);
	void build_hierarchy_toolbar(BoxContainer *p_parent);
	void hierarchy_filter_action(int p_action);
	void hierarchy_quick_filter(bool p_enabled,int p_kind);
	void hierarchy_tool_action(int p_action);
	bool run_workspace_tools_self_test();
	bool run_slot_hierarchy_self_test();
	void open_find_replace();
	void refresh_find_replace();
	void apply_find_replace();
	void select_find_results(bool p_selected);
	int hierarchy_entity_kind(const Dictionary &p_entity) const;
	void filter_hierarchy(const String &p_filter);
	void fold_hierarchy(bool p_collapsed);
	int image_selection=-1;
	ConfirmationDialog *binding_dialog=nullptr;
	ItemList *binding_bones=nullptr;
	int binding_rig=-1;
	CheckBox *mesh_edit=nullptr;
	HBoxContainer *image_tools=nullptr;
	void image_action(int p_action);
	void images_dropped(const PackedStringArray &p_paths,const Vector2 &p_position);
	void external_images_dropped(const PackedStringArray &p_paths);
	void apply_binding();
	void mesh_toggled(bool p_enabled);
	void mesh_changed(int p_entity,const Dictionary &p_polygon);
	int find_rig(int p_entity) const;
	static Dictionary subdivide_mesh(const Dictionary &p_polygon);
	Button *mode_button=nullptr;
	Label *animation_title=nullptr;
	Label *selection_title=nullptr;
	Vector<Button *> animation_buttons;
	bool animation_mode=false, playing=false, refreshing=false;
	double playback_time=0;
	Vector2i selected_key=Vector2i(-1,-1);
	String editing_state;
	Ref<Animation> current_clip() const;
	void set_mode(int p_mode);
	void toggle_authoring_mode();
	void hierarchy_selected();
	void choose_animation(int p_index);
	void seek(double p_time);
	void select_key(int p_track,int p_key);
	void move_key(int p_track,int p_key,double p_time);
	void pose_edited(int p_entity,const String &p_field,const Vector3 &p_value);
	void save_scene();
	Ref<ECSScene> scene;
	ECSUICanvasEditor *canvas=nullptr;
	ECSUICanvasEditor *local_canvas=nullptr;
	void select_target(int p_index);
	OptionButton *owner=nullptr,*target=nullptr,*property=nullptr,*states=nullptr;
	SpinBox *time=nullptr,*x=nullptr,*y=nullptr,*z=nullptr,*duration=nullptr;
	LineEdit *state_name=nullptr,*event_name=nullptr,*event_text=nullptr;
	SpinBox *event_integer=nullptr,*event_number=nullptr;
	void insert_channel_key(const String &p_field,const Variant &p_value);
	SpinBox *clip_length=nullptr;
	CheckBox *clip_loop=nullptr;
	bool configure_animation(const String &p_name,double p_length,bool p_loop,bool p_create,String &r_error);
	Label *feedback=nullptr;
	void action(int p_action);
	void refresh_tracks(int p_unused=0);
	void commit_animation(const Dictionary &p_definition,const String &p_label,bool p_edit_clip=true);
protected:
	static void _bind_methods() {}
	void _notification(int p_what);
public:
	ECSAnimationEditor();
	bool run_self_test();
	void start_independent_project(const Ref<ECSScene> &p_scene);
	bool prepare_platform_export();
	void stop_preview();
	void edit_scene(const Ref<ECSScene> &p_scene,ECSUICanvasEditor *p_canvas);
};
#endif
